### ISSUE TITLE
Add dependency of Ubuntu in README

### ISSUE THREAD

**Issue by blueskyson** [marchersimon/tldr-cpp#3]
Installing these dependencies prior to `make build` in Ubuntu.

```
sudo apt install libcurl4-openssl-dev libzip-dev
```

**Comment by marchersimon** [comment]
Thanks! Any reason you chose the `dev` variant of those packages? Are those the defaults for ubuntu? Also, are these packages already preinstalled? (In that case I'll just add a note to make sure they're there)

**Comment by blueskyson** [comment]
1. Only *-dev packages contain required headers like `zip.h` and `curl/curl.h`.
2. `Zip` and `curl` binaries might be default, but their libraries are not default. 
3. At least the 2 packages are not default in my Ubuntu 20.04 (August 2020 release version).

There is no need to worry about whether they are default. If the machine already contains those libraries, `apt` will cancel installation or ask user to update to prevent conflicts.

**Comment by marchersimon** [comment]
Ah, I thought `dev` means it is in development rather it is used for development. Makes more sense now. I'll add it 👍🏽

**Comment by marchersimon** [comment]
Done in  0bab3ba
