### ISSUE TITLE
'git tag' the release and use a proper pkgver() in the pkgbuild

### ISSUE THREAD

**Issue by FabioLolix** [marchersimon/tldr-cpp#5]
https://aur.archlinux.org/packages/tldr-cpp-git/#comment-823151

**Comment by marchersimon** [comment]
Why do the examples [here](https://wiki.archlinux.org/title/VCS_package_guidelines#Git) use `--long`? Could I just do this:
```
pkgver() {
  cd "$pkgname"
  git describe --tags
}
```
and then I just tag my commits with `git tag 1.X`. 
Then my package name won't be `0.71.r115.gd95ee07-1`, but just `1.X-1`.

**Comment by marchersimon** [comment]
It has been working for a while, so I'll close this now.

**Comment by FabioLolix** [comment]
> Then my package name won't be `0.71.r115.gd95ee07-1`, but just `1.X-1`

Being just `1.X-1`is wrong, the pkgver need to be like `0.71.r115.gd95ee07-1`

**Comment by marchersimon** [comment]
I've now found a way to keep it simple, but still differentiate between commits:
> ( git tag | tail -n 1 ; echo "." ; git rev-list $(git tag | tail -n 1)..HEAD --count ) | tr -d '\n'

For example for the 2nd commit since 1.7, this will set pkgver to 1.7.2-1

**Comment by FabioLolix** [comment]
Using the standard pkgver works fine

>   git describe --long --tags | sed 's/\([^-]*-g\)/r\1/;s/-/./g'

> 1.7.r5.g10e3a24
